#!/usr/bin/env bash

export NODE_ENV=production

rm -f posts.json && touch posts.json

docker-compose up -d --build

sleep 1

attempts=0
maxAttempts=25
while ! [ -s "posts.json" ] && [ $attempts -le $maxAttempts ]; do
  attempts+=1
  echo "waiting for posts to be exported..."
  sleep 1
done

docker-compose logs --no-color >& logs.txt
docker-compose stop

next build && next export -o dist
