version: "3.7"

services:
  proxy:
    image: traefik:v2.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/config/${NODE_ENV}/traefik.yml:/etc/traefik/traefik.yml
      - ${PWD}/acme.json:/acme.json
    labels:
      traefik.http.routers.proxy.rule: Host(`traefik.${DOMAIN}`)
      traefik.http.services.proxy.loadbalancer.server.port: 8080

  ghost:
    image: ghost:3-alpine
    restart: unless-stopped
    volumes:
      - ./themes/:/var/lib/ghost/content/themes/
      - ./content/:/var/lib/ghost/content/
    environment:
      NODE_ENV: ${NODE_ENV}
      url: ${PROTO}://${DOMAIN}
    labels:
      traefik.http.routers.ghost.rule: Host(`${DOMAIN}`)
      traefik.http.services.ghost.loadbalancer.server.port: 2368

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/lib/mysql
    labels:
      traefik.enable: false

  spiral:
    image: brymastr/spiral
    restart: unless-stopped
    labels:
      traefik.http.routers.spiral.rule: Host(`spiral.${DOMAIN}`)

  primes:
    image: brymastr/primes
    restart: unless-stopped
    labels:
      traefik.http.routers.primes.rule: Host(`primes.${DOMAIN}`)

  halloween:
    build: ./halloween/
    restart: unless-stopped
    labels:
      traefik.http.routers.primes.rule: Host(`halloween.${DOMAIN}`)

  whoami:
    image: containous/whoami
    labels:
      traefik.http.routers.whoami.rule: Host(`whoami.${DOMAIN}`)

volumes:
  data:
