version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "blog-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9hep6u2wm2mb"
s3_prefix = "blog-dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
fail_on_empty_changeset=false
parameter_overrides = "HostedZoneId=\"Z05558683FC949RPHCKBP\" DomainName=\"dev.dorsay.dev\""

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "blog-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9hep6u2wm2mb"
s3_prefix = "blog-prod"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
fail_on_empty_changeset=false
parameter_overrides = "HostedZoneId=\"Z05558683FC949RPHCKBP\" DomainName=\"dorsay.dev\""
