#!/usr/bin/env bash

touch posts.json

docker-compose up -d --build

sleep 2

postsUrl="http://localhost:3001/ghost/#/posts"

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  sensible-browser $postsUrl
elif [[ "$OSTYPE" == "darwin"* ]]; then
  open $postsUrl
else
  echo What... windows? lol
  exit 1
fi


docker-compose logs webhook

docker attach blog_webhook_1

function cleanup {
  docker-compose down
}

trap cleanup EXIT
