#!/usr/bin/env bash

touch posts.json

docker-compose up -d --build

sleep 2

sensible-browser "http://localhost:3001/ghost/#/posts"

docker attach blog_webhook_1

function cleanup {
  docker-compose down
  rm posts.json
}

trap cleanup EXIT
