#!/usr/bin/env bash

input=\"$1\"
output=$(grep -A 2 "service $input" .dockermodules)
repo=$(echo $output | sed -E 's/^.*repo\s*=\s*([a-zA-Z|/-]+).*$/\1/')
path=$(echo $output | sed -E 's/^.*path\s*=\s*([a-zA-Z|/-]+).*$/\1/')

trap "docker-compose -f compose/build.yml --project-name pipeline stop $1" SIGHUP SIGINT SIGTERM

cp env/local/.env .env

nodemon \
  --exec "docker-compose \
    -f compose/build.yml \
    --project-name pipeline \
    up --build --force-recreate --remove-orphans $1" \
  --signal SIGINT \
  --watch "$path" \
  --ext js,json,cs,csproj,vue,Dockerfile

rm .env